apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis
      envFrom:
      - secretRef:
          name: db-secret
      - secretRef:
          name: sys-secret

